Import libraries


In [ ]:
import pandas as pd
import numpy as np

Create raw data

In [ ]:
data = {
    "Student_ID": range(1,26 ),

    "Gender": [
        "Female", "Male", "Female", "Male", "Female",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Department": [
        "Data Science", "Computer Science", "Data Science", "Statistics", "Computer Science",
        "Data Science", "Statistics", "Computer Science", "Data Science", "Statistics",
        "Computer Science", "Data Science", "Statistics", "Computer Science", "Data Science",
        "Statistics", "Computer Science", "Data Science", "Statistics", "Computer Science",
        "Data Science", "Statistics", "Computer Science", "Data Science", "Statistics"
    ],

    "Age": [
        21, 22, 20, 23, 21,
        22, 24, 20, 21, 23,
        22, 21, 24, 20, 22,
        23, 21, 22, 20, 24,
        21, 23, 22, 20, 21
    ],

    "Study_Hours": [
        5, 7, 4, 8, 6,
        5, 9, 3, 7, 6,
        8, 5, 6, 4, 7,
        9, 5, 8, 6, 4,
        7, 6, 5, 8, 4
    ],

    "Marks": [
        78, 85, 72, 91, 80,
        75, 94, 68, 88, 82,
        90, 77, 84, 70, 86,
        93, 79, 87, 76, 73,
        89, 81, 78, 92, 69
    ]
}


Convert raw data into DataFrame

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

,Student_ID,Gender,Department,Age,Study_Hours,Marks
0,1,Female,Data Science,21,5,78
1,2,Male,Computer Science,22,7,85
2,3,Female,Data Science,20,4,72
3,4,Male,Statistics,23,8,91
4,5,Female,Computer Science,21,6,80
5,6,Female,Data Science,22,5,75
6,7,Male,Statistics,24,9,94
7,8,Female,Computer Science,20,3,68
8,9,Male,Data Science,21,7,88
9,10,Female,Statistics,23,6,82


In [ ]:
print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

print("\nDataset Information:")
df.info()

First 5 rows:


,Student_ID,Gender,Department,Age,Study_Hours,Marks
0,1,Female,Data Science,21,5,78
1,2,Male,Computer Science,22,7,85
2,3,Female,Data Science,20,4,72
3,4,Male,Statistics,23,8,91
4,5,Female,Computer Science,21,6,80


Last 5 rows:


,Student_ID,Gender,Department,Age,Study_Hours,Marks
20,21,Female,Data Science,21,7,89
21,22,Male,Statistics,23,6,81
22,23,Female,Computer Science,22,5,78
23,24,Male,Data Science,20,8,92
24,25,Female,Statistics,21,4,69



Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Student_ID   25 non-null     int64 
 1   Gender       25 non-null     object
 2   Department   25 non-null     object
 3   Age          25 non-null     int64 
 4   Study_Hours  25 non-null     int64 
 5   Marks        25 non-null     int64 
dtypes: int64(4), object(2)
memory usage: 1.3+ KB


In [ ]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 25
Number of columns: 6


In [ ]:
numeric_data = df[
    ["Age", "Study_Hours", "Marks"]
]

X = numeric_data.to_numpy()

print(X)

[[21  5 78]
 [22  7 85]
 [20  4 72]
 [23  8 91]
 [21  6 80]
 [22  5 75]
 [24  9 94]
 [20  3 68]
 [21  7 88]
 [23  6 82]
 [22  8 90]
 [21  5 77]
 [24  6 84]
 [20  4 70]
 [22  7 86]
 [23  9 93]
 [21  5 79]
 [22  8 87]
 [20  6 76]
 [24  4 73]
 [21  7 89]
 [23  6 81]
 [22  5 78]
 [20  8 92]
 [21  4 69]]


In [ ]:
print("Shape:", X.shape)
print("Size:", X.size)
print("Number of dimensions:", X.ndim)

Shape: (25, 3)
Size: 75
Number of dimensions: 2


In [ ]:
A = X[:4, :]
B = X[4:8, :]

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[21  5 78]
 [22  7 85]
 [20  4 72]
 [23  8 91]]

Matrix B:
[[21  6 80]
 [22  5 75]
 [24  9 94]
 [20  3 68]]


In [ ]:
addition = A + B

print("A + B =")
print(addition)

A + B =
[[ 42  11 158]
 [ 44  12 160]
 [ 44  13 166]
 [ 43  11 159]]


In [ ]:
subtraction = A - B

print("A - B =")
print(subtraction)

A - B =
[[  0  -1  -2]
 [  0   2  10]
 [ -4  -5 -22]
 [  3   5  23]]


In [ ]:
multiplication = A * B

print("Element-wise multiplication A * B =")
print(multiplication)

Element-wise multiplication A * B =
[[ 441   30 6240]
 [ 484   35 6375]
 [ 480   36 6768]
 [ 460   24 6188]]


In [ ]:
matrix_product = np.dot(A, B.T)

print("Matrix product A × Bᵀ =")
print(matrix_product)

Matrix product A × Bᵀ =
[[6711 6337 7881 5739]
 [7304 6894 8581 6241]
 [6204 5860 7284 5308]
 [7811 7371 9178 6672]]


In [ ]:
transpose_A = A.T

print("Transpose of A:")
print(transpose_A)

Transpose of A:
[[21 22 20 23]
 [ 5  7  4  8]
 [78 85 72 91]]


In [ ]:
print("Original shape:", A.shape)
print("Transpose shape:", A.T.shape)

Original shape: (4, 3)
Transpose shape: (3, 4)


In [ ]:
M = X[:3, :3]

print("Matrix M:")
print(M)

print("\nShape of M:")
print(M.shape)

print("\nDeterminant of M:")
print(np.linalg.det(M))

Matrix M:
[[21  5 78]
 [22  7 85]
 [20  4 72]]

Shape of M:
(3, 3)

Determinant of M:
-31.9999999999999


In [ ]:
M_inverse = np.linalg.inv(M)

print("Inverse of M:")
print(M_inverse)

Inverse of M:
[[-5.125    1.5      3.78125]
 [-3.625    1.5      2.15625]
 [ 1.625   -0.5     -1.15625]]


In [ ]:
identity_check = np.dot(M, M_inverse)

print("M × M_inverse =")
print(identity_check)

M × M_inverse =
[[ 1.00000000e+00  4.44089210e-15  7.10542736e-15]
 [ 7.54951657e-15  1.00000000e+00 -3.55271368e-15]
 [ 3.55271368e-15  3.55271368e-15  1.00000000e+00]]


In [ ]:
print(df[["Gender", "Department"]].head(10))

   Gender        Department
0  Female      Data Science
1    Male  Computer Science
2  Female      Data Science
3    Male        Statistics
4  Female  Computer Science
5  Female      Data Science
6    Male        Statistics
7  Female  Computer Science
8    Male      Data Science
9  Female        Statistics


In [ ]:
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()
encoder = LabelEncoder()
df_encoded["Gender"] = encoder.fit_transform(df_encoded["Gender"])
df_encoded["Department"] = encoder.fit_transform(df_encoded["Department"])


In [ ]:
display(df_encoded.head(10))

,Student_ID,Gender,Department,Age,Study_Hours,Marks
0,1,0,1,21,5,78
1,2,1,0,22,7,85
2,3,0,1,20,4,72
3,4,1,2,23,8,91
4,5,0,0,21,6,80
5,6,0,1,22,5,75
6,7,1,2,24,9,94
7,8,0,0,20,3,68
8,9,1,1,21,7,88
9,10,0,2,23,6,82
